# roll, pitch, yaw
# float[9]
imu_orientation_covariance: [0.1, 0, 0,
                             0, 0.1, 0,
                             0, 0, 0.1]

# roll, pitch, yaw
# float[9]
imu_angular_velocity_covariance: [0.01, 0, 0,
                                  0, 0.01, 0,
                                  0, 0, 0.03]

# x, y, z
# float[9]
imu_linear_acceleration_covariance: [0.1, 0, 0,
                                     0, 0.1, 0,
                                     0, 0, 0.4]

# x, y, z, roll, pitch, yaw
# float[36]
pose_covariance: [0.1404, 0, 0, 0, 0, 0,
                  0, 0.1404, 0, 0, 0, 0,
                  0, 0, 0.1404, 0, 0, 0,
                  0, 0, 0, 0.0004, 0, 0,
                  0, 0, 0, 0, 0.0004, 0,
                  0, 0, 0, 0, 0, 0.0004]
