# TODO We aren't really running in a two d enviornment, but we don't really
# Have a good way to localize in three dimensions, so for now we're going to
# pretend to be running in a planar enviornment. We might be able to release
# this constraint in the global localization.
two_d_mode: false

# robot_localization produces transform from world frame to base_link frame
map_frame: map
odom_frame: odom
base_link_frame: base_link

# Wheel odometry
# We discard position estimates from wheel odometry
# because the same data is already reported in velocity
odom0: /chassis_controller/odom
odom0_config: [false, false, false, # x, y, z
               false, false, false, # r, p, y
               true,  true,  true,  # dx, dy, dz
               false, false, true,  # dr, dp, dy
               false, false, false] # d^2x, d^2y, d^2z

# Body IMU
imu0: /imu_data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              false, false, false,
              true, true, true]

world_frame: odom
