state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

chassis_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 10
    left_wheel: 'left_wheel_joint'
    right_wheel: 'right_wheel_joint'
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    enable_odom_tf: false
    wheel_separation_multiplier: 1.05

simon_arm_controller:
    type: "position_controllers/JointPositionController"
    joint: simon_arm_joint

left_paddle_controller:
    type: "position_controllers/JointPositionController"
    joint: left_paddle_joint

right_paddle_controller:
    type: "position_controllers/JointPositionController"
    joint: right_paddle_joint
