TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5
  min_vel_theta: -0.7
  max_vel_theta: 0.7
  min_in_place_vel_theta: 0.3

  escape_vel: -0.3

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  meter_scoring: true

  holonomic_robot: false
