footprint: [[0.38, 0.38], [0.38, -0.38], [-0.38, -0.38], [-0.38, 0.38]]
#[[0.359537, 0.34925], [0.359537, -0.34925], [-0.359537, -0.34925], [-0.359537, 0.34925]]
transform_tolerance: 0.5

obstacle_range: 2.5
raytrace_range: 3.0

map_type: costmap

obstacle_layer:
  enabled: true
  track_unknown_space: true
  observation_sources: front_lidar
  front_lidar:
    sensor_frame: laser_link
    data_type: PointCloud2
    topic: cloud_filtered
    marking: true
    clearing: true

static_layer:
  enabled: true

inflation_layer:
  enabled: true
  inflation_radius: 0.55
  cost_scaling_factor: 10

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  plugins:
    - {name: static_layer,          type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

plugins:
  - {name: static_layer,          type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

