#base_local_planner: teb_local_planner/TebLocalPlannerROS 

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.3
  min_vel_theta: -0.5
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.3

  escape_vel: -0.3
  meter_scoring: true

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  holonomic_robot: false
    
TebLocalPlannerROS:
   footprint_model:
     type: "polygon"
     vertices: [[0.38, 0.38], [0.38, -0.38], [-0.38, -0.38], [-0.38, 0.38]]

   acc_lim_x: 1.0
   acc_lim_theta: 1.0

   max_vel_x: 0.5
   max_vel_x_backwards: 0.3
   max_vel_theta: 0.7

   min_turning_radius: 0.0

   xy_goal_tolerance: 0.1
   yaw_goal_tolerance: 0.2

   min_samples: 5
   max_global_plan_lookahead_dist: 5
   publish_feedback: true
   allow_init_with_backwards_motion: true

   min_obstacle_dist: 0.3
   inflation_dist: 0.0
   include_dynamic_obstacles: true

