#Full params: http://wiki.ros.org/teb_local_planner
TebLocalPlannerROS:
   footprint_model: # types: "point", "circular", "line", "two_circles", "polygon"
     type: "polygon"
   #radius: 0.2 # for type "circular"
   #line_start: [-0.3, 0.0] # for type "line"
   #line_end: [0.3, 0.0] # for type "line"
   #front_offset: 0.2 # for type "two_circles"
   #front_radius: 0.2 # for type "two_circles"
   #rear_offset: 0.2 # for type "two_circles"
   #rear_radius: 0.2 # for type "two_circles"
     vertices: [[0.38, 0.38], [0.38, -0.38], [-0.38, -0.38], [-0.38, 0.38]] # for type "polygon"

   acc_lim_x: 1.0
   acc_lim_theta: 1.0

   max_vel_x: 0.5
   max_vel_x_backwards: 0.3
   max_vel_theta: 0.7

   min_turning_radius: 0.0 #set to zero for a diff-drive robot

   xy_goal_tolerance: 0.2
   yaw_goal_tolerance: 0.2

   min_samples: 5
   max_global_plan_lookahead_dist: 5
   publish_feedback: true
   allow_init_with_backwards_motion: true

   min_obstacle_dist: 0.3
   inflation_dist: 0.5
   include_dynamic_obstacles: true

   #costmap_converter_plugin:
