initial_pose:
  position:
    x: -2.4384
    y:  2.4384
    z:  0.6604
  orientation:
    y: 135

ball_pit:
  position:
    x: -2.4
    y:  1.219
    z:  0.6604
  orientation:
    y: 180

ramp_close_top:
  position:
    x: -2.4
    y:  2.4
    z:  0.6604

ramp_close_bottom:
  position:
    x: -5.0
    y:  5.0
    z:  0.0

bridge_close:
  position: 
    x: -5.486
    y: 2.500
    z:  0.000

bridge_far:
  position: 
    x: -5.486
    y: -2.500
    z:  0.000

ramp_far_top:
  position: 
    x: -2.4
    y: -2.4
    z:  0.6604

ramp_far_bottom:
  position: 
    x: -5.0
    y: -5.0
    z:  0.0

simon_approach:
  position: 
    x: -4.000
    y: -5.70
    z:  0.000
  orientation: 
    y: 180
